# Generated by Django 3.1.5 on 2021-03-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('importance', models.CharField(choices=[('Not Important Not Urgent', 'Not Important Not Urgent'), ('Urgent but Not Important', 'Urgent but Not Important'), ('Important but Not Urgent', 'Important but Not Urgent'), ('Important and Urgent', 'Important and Urgent')], max_length=50)),
                ('lifeArea', models.CharField(choices=[('Personal', 'Personal'), ('Family', 'Family'), ('Career', 'Career'), ('Hobby', 'Hobby')], max_length=20)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
