# Generated by Django 3.1.5 on 2021-03-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='showInToday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
