# Generated by Django 3.1.5 on 2021-06-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
