# Generated by Django 3.1.5 on 2021-06-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(default='', max_length=8),
        ),
    ]
