# Generated by Django 3.1.5 on 2021-09-10 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.CharField(default='', max_length=8)),
                ('importance', models.CharField(choices=[('Not Important Not Urgent', 'Not Important Not Urgent'), ('Urgent but Not Important', 'Urgent but Not Important'), ('Important but Not Urgent', 'Important but Not Urgent'), ('Important and Urgent', 'Important and Urgent')], max_length=50)),
                ('lifeArea', models.CharField(choices=[('Personal', 'Personal'), ('Family', 'Family'), ('Career', 'Career'), ('Hobby', 'Hobby')], max_length=20)),
                ('key', models.IntegerField()),
                ('showInToday', models.BooleanField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
